### ISSUE TITLE
Upload d'image page d'accueil

### ISSUE THREAD

**Issue by sblondeau** [WildCodeSchool/orleans-0917-leven#24]
J'essaie d'uploader une photo .jpg de 50ko et j'ai le message d'erreur
Erreur lors de l'envoi du fichier 'leven1.jpg'.
et ça ne fonctionne pas

**Comment by benjahdev** [comment]
Bonjour monsieur, désolé pour cela, notre serveur n'était pas correctement installé... Tout devrait être fonctionnel maintenant, bonne navigation sur leven.fr!
